---
name: datascience
full_name: Data Services Working Group
description:
  Data enthusiasts welcome. Learn, share, geek out about data methods and projects here.
private:
  slack: wg-dataservices
owner_type: working-group
